### ISSUE TITLE
Add count direction to table results and sort date on unique locations

### ISSUE THREAD

**Issue by seandoesgis** [DVRPCfreight/TrafficCountConcept#36]
If count has N,E,W,S direction, add cntdir to road name if possible.

Sort date for unique location if possible.
![capture](https://cloud.githubusercontent.com/assets/16228607/12425759/56b0f1d0-bea4-11e5-8bb6-5e4a69a2f2f2.PNG)

**Comment by wtsay** [comment]
https://github.com/DVRPCfreight/TrafficCountConcept/commit/c0a55c9519349f2530901a4dbdfb5c136db5813c

Demo: http://orephik.com/tcc_c0a55c9/

Could add more logic to only grab first letter of CNTDIR and append with "B"

**Comment by DVRPCfreight** [comment]
Count direction fixed in c0a55c9519349f2530901a4dbdfb5c136db5813c and 731b5329322d72ee11c289270e07ff1deb382fd9

**Comment by wtsay** [comment]
https://github.com/DVRPCfreight/TrafficCountConcept/commit/b39356722363fac34469cc429fd4ca512665c09b

Demo: http://orephik.com/tcc_b393567/

Changed the highlighting of records in DataTable conditions to only exact matches (otherwise it would appear that the sorting does not work).
Added secondary sorting conditions to sort on recnum (proxy of count date) if the elapsed distances between points is the same (from the click location).

**Comment by wtsay** [comment]
Of course, it is probably possible to add in some sort of fudge factor to group results by (say if distance is within _x_ somethings, group together) instead of mathematically identical lat/lons.

**Comment by DVRPCfreight** [comment]
Fixed by f9b2d1626bb5a1756842a466dabead76616dc08b

**Comment by seandoesgis** [comment]
You guys are good.  Like really really good...nice work.
