### ISSUE TITLE
Add ability for users to change symbol size based on AADT

### ISSUE THREAD

**Issue by crvanpollard** [DVRPCfreight/TrafficCountConcept#59]
- Add smart mapping capability to allow users to quickly symbolize the traffic counts based off 'AADT' using graduated/proportional symbols (use quantiles classification method).
- Color will remain the same
- This tutorial may give some insight into how to call the 'createPropSymbols() function'
  [http://www.cartographicperspectives.org/index.php/journal/article/view/cp76-donohue-et-al/1307](url) 
  <img width="1059" alt="screen shot 2016-04-09 at 9 32 23 pm" src="https://cloud.githubusercontent.com/assets/4401281/14407520/a00cdf16-fe9a-11e5-8d6b-a33cdadb9e0c.png">

**Comment by wtsay** [comment]
What does this accomplish though?
Unless you have the perfect set of filters, this seems like it would create confusion very easily.

Off the top of me noggin...
- 'You' would most likely want to have a certain year in mind - effectively you would want to add in a temporal axis to the data. Otherwise showing concentric circles of varying size is confusing.
- 'You' would probably want different scales/circle radii based on traffic count density on the map.
- 'You' would need to be careful about overlapping circles. Some logic would be needed to add in layers by AADT ascending to minimise circles masking other circles.

All this being said, I would assume that someone who knows how to create a meaningful map to display this sort of data will use a more advanced (and suitable) tool to generate such a map. It just seems like adding in this feature will create more confusion than be useful.

And I don't think it's that hard to vary the circle size by some attribute.
Demo: http://wololo.co/TCC_circles/

**Comment by crvanpollard** [comment]
<img width="554" alt="screen shot 2016-04-18 at 2 18 56 pm" src="https://cloud.githubusercontent.com/assets/4401281/14614791/a81d931c-0570-11e6-9bb9-da41da0f30dc.png">
I agree that the right set of filters and a specific focus is needed. My vision/reasoning was I am a traffic engineer/planner in a township and I want to visualize all the Volume Counts in my area and see the top locations or areas with the highest amount of AADT quickly.
May be we add in a way to 'Filter the Results' based on operations? (< 45,000 or >10,00)?

**Comment by crvanpollard** [comment]
not enough reasoning and importance to added this functionailty but something that was worthing discussing #close 59

**Comment by DVRPCfreight** [comment]
Maybe we just ice this for now..could be a future component in the advanced toolset?
